PRAGMA foreign_keys=OFF;
CREATE TABLE host_group(id INTEGER PRIMARY KEY NOT NULL, parent INTEGER REFERENCES host_groups(id), name TEXT);
CREATE TABLE host(id INTEGER PRIMARY KEY NOT NULL, name TEXT);
CREATE TABLE variable(id INTEGER PRIMARY KEY NOT NULL, name TEXT);
CREATE TABLE service(id INTEGER PRIMARY KEY NOT NULL, name TEXT, parent references service(id));
CREATE TABLE host_variable(variable INTEGER NOT NULL REFERENCES variable(id), host INTEGER NOT NULL REFERENCES host(id), value TEXT NOT NULL, PRIMARY KEY (variable, host));
CREATE TABLE service_variable(variable INTEGER NOT NULL REFERENCES variable(id), "service" INTEGER NOT NULL REFERENCES "service"(id), value TEXT NOT NULL, PRIMARY KEY (variable, "service"));
CREATE TABLE service_instance(id INTEGER PRIMARY KEY NOT NULL, "service" INTEGER NOT NULL REFERENCES "service"(id), host INTEGER NOT NULL REFERENCES host(id), ip TEXT NOT NULL, name TEXT NOT NULL, unique(service, host, name));
CREATE TABLE service_instance_variable(variable INTEGER NOT NULL REFERENCES variable(id), instance INTEGER NOT NULL REFERENCES service_instance(id), value TEXT NOT NULL, primary key (variable, instance));
CREATE TABLE host_group_variable(variable INTEGER NOT NULL REFERENCES variable(id), "group" INTEGER NOT NULL REFERENCES "group"(id), value TEXT NOT NULL, PRIMARY KEY (variable, "group"));
CREATE TABLE host_group_membership(host integer references host(id), "group" integer references host_group(id), primary key (host, "group"));
CREATE TABLE db_version(key text primary key NOT NULL check (key = 'single-row'), version integer);
INSERT INTO db_version VALUES('single-row',1);
